%let macrodir=/home/cheng.zhong.shan/Macros;
%include "&macrodir/importallmacros_ue.sas";
/* options mprint mlogic symbolgen; */
%importallmacros_ue;
libname GTEX '/home/cheng.zhong.shan/data/GTEx_V8';
 
*Note: the input gene order will be used to draw boxplots from up to down;
%let genes=EXOC6B CYP26B1 DYSF;
*%let genes=MAP3K19 CXCR4;
 
*After running the follwoing macro once, it would be runnable again;
*by adjust the parameters of UseGeneratedDsd and Lib4PreviousDsd;
*with generated dataset exp_all;
*Even the 1st run may fail, once exp_all is generated, the macro can run it for it!;
/* %Boxplots4GenesInGTExV8ByGrps( */
/* genes=&genes, */
/* dsdout=exp, */
/* bygrps=AA, */
/* UseGeneratedDsd=1, */
/* PreviousDsd=tgt, */
/* Lib4PreviousDsd=GTEx, */
/* WhereFilters4Boxplot=%str( AA in ('AA','EA')), */
/* boxplot_width=1800, */
/* boxplot_height=1000 */
/* ); */
/* proc print data=tgt(obs=10);run; */
/* proc sort data=tgt;by rownames cluster AA; */
/* ods graphics on/reset=all noborder; */
/* proc glm data=tgt; */
/* where AA in ('EA','AA'); */
/* class AA; */
/* model exp=AA; */
/* lsmeans AA/pdiff; */
/* by rownames cluster; */
/* run; */

%Boxplots4GenesInGTExV8ByGrps(
genes=&genes,
dsdout=exp,
bygrps=sex,
UseGeneratedDsd=0,
PreviousDsd=tgt,
Lib4PreviousDsd=GTEx,
WhereFilters4Boxplot=%str( ),
boxplot_width=1800,
boxplot_height=1000
);


proc print data=tgt(obs=10);run;
proc sort data=tgt;by rownames cluster sex;
ods graphics on/reset=all noborder;
proc glm data=tgt;
where AA in ('EA','AA');
class sex;
model exp=sex;
lsmeans sex/pdiff;
by rownames cluster;
run;


*****************Tested codes;
*******************Run with downloaded data****************************;
*options mprint mlogic symbolgen;
%let macrodir=/home/cheng.zhong.shan/Macros;
%include "&macrodir/importallmacros_ue.sas";
%importallmacros_ue;
libname GTEX '/home/cheng.zhong.shan/data/GTEx_V8';

*Note: the input gene order will be used to draw boxplots from up to down;
%let genes=EXOC6B CYP26B1 DYSF;
*%let genes=MAP3K19 CXCR4;

*After running the follwoing macro once, it would be runnable again;
*by adjust the parameters of UseGeneratedDsd and Lib4PreviousDsd;
*with generated dataset exp_all;
*Even the 1st run may fail, once exp_all is generated, the macro can run it for it!;
%Boxplots4GenesInGTExV8ByGrps(
genes=&genes,
dsdout=exp,
bygrps=sex,
UseGeneratedDsd=0,
PreviousDsd=tgt,
Lib4PreviousDsd=GTEx,
WhereFilters4Boxplot=%str(),
boxplot_width=1800,
boxplot_height=2000
);

*Get subset genes for using them later;
*exp_all was generated by the above sas macro internally;
proc print data=exp_all(obs=10);var rownames;run;
data GTEX.target_genes;
set exp_all;
where scan(rownames,2,'|') in (
'APOBEC3A',
'APOBEC3B',
'APOBEC3C',
'APOBEC3D',
'APOBEC3F',
'APOBEC3G',
'APOBEC3H'
);
run;


*******************Run with generated data****************************;

%let macrodir=/home/cheng.zhong.shan/Macros;
%include "&macrodir/importallmacros_ue.sas";
%importallmacros_ue;

libname GTEX '/home/cheng.zhong.shan/data/GTEx_V8';

*Note: the input gene order will be used to draw boxplots from up to down;
%let genes=EXOC6B CYP26B1 DYSF;
*%let genes=MAP3K19 CXCR4;
data exp_all;set GTEX.target_genes;run;
data headers;set GTEX.headers;run;
*Use generated dataset exp_all or GTEX.target_genes;
*options mprint mlogic symbolgen;
*The macro is with bug, when using previously generated dsd;
*Need to asign dsdout exp_all and PreviousDsd as empty string;
*The bug is due to the macro var PreviousDsd is fixed to be 'tgt';
*So it is arbitary to asign macro var PreviousDsd as 'tgt' whenever using previous dsd;
/* %debug_macro; */
%OpenSVG_Printer;
%Boxplots4GenesInGTExV8ByGrps(
genes=&genes,
dsdout=exp_all,
bygrps=AA,
UseGeneratedDsd=1,
PreviousDsd=tgt,
Lib4PreviousDsd=work,
WhereFilters4Boxplot=%str( AA in ("AA","EA") and 
cluster in ("Whole Blood","Lung","Spleen","Liver","Artery Tibial","Pancreas")
),
boxplot_width=500,
boxplot_height=800
);
%CloseSVG_Printer;

data tgt;
set tgt;
rownames1=trim(left(rownames))||"_"||AA;
run;

%let var=rownames;
/* %let var=rownames1; */
/* proc print data=tgt(obs=10);run; */
proc sql;
create table median_exp as
select distinct cluster,&var,median(exp) as exp
from tgt
group by cluster,&var;
/* proc print data=median_exp(obs=10);run; */
%OpenSVG_Printer;
%clustergram4longformatdsd(
dsdin=median_exp,/*The input dataset is a matrix contains rownames and other numeric columns*/
rowname_var=&var,/*the elements of rowname_var will be used to label heatmap columns*/
colname_var=cluster,/*These column-wide names will be used to label heatmap rowlabels*/
value_var=exp,/*numeric data for heatmap cells*/
height=40,/*figure height in cm*/
width=25,/*figure width in cm*/
columnweights=0.15 0.85, /*figure 2 column ratio*/
rowweights=0.05 0.95, /*figure 2 row ratio*/
cluster_type=3        /*values are 0, 1, 2, and 3 for not clustering heatmap, 
                       clustering heatmap by column, row, and both*/
);
%CloseSVG_Printer;
/*
*Need to add the AA info into the umap dataset for the following glm macro;
*options mprint mlogic symbolgen;
%sc_glm4genes(
dsd=GTEX.target_genes,
dsd_headers=GTEX.headers,
dsd_umap=GTEX.umap,
genes=&genes,
GLMStatOutDsd=GLMStatOut,
GLM_classes=cluster sex,
GLM_model=cluster sex,
samplewide=0,
sample_var=sample,
pheno_var=sex,
where_condition=
);
*/
*options mprint mlogic symbolgen;
data tgt;
set tgt;
where AA in ('EA','AA');
run;
%debug_macro;
%glm_by_grps(
dsd=tgt,
grpvars=rownames cluster,
yvar4glm=exp,
GLMStatOutDsd=GLMStatOut,
GLM_classes=AA,
GLM_model=AA,
pheno_var=AA, 
where_condition=
);
 

*Make heatmap;
data dsd4heatmap (keep=rownames cluster logP);
set GLMStatOut;
logP=-log10(probF);
*if logP<-log10(0.05/(12*21)) then logp=.;
*cutoff p=1.45x10-4;
if logP<-log10(0.05/(49*7)) then logp=.;
if logP>50 then logP=50;
cluster=prxchange('s/[\W\s]+/_/',-1,cluster);
cluster=prxchange('s/_\b//',-1,cluster);
where source="AA" and
Cluster not contains 'Outlier';
label Cluster="Tissue types" rownames="Genes"
logP="ANOVA -log10(P)";
run;

*Only keep these tissues with at least one genes showing significant differential expression between AA and EA;
proc sql;
create table dsd4heatmap as
select *
from dsd4heatmap
group by rownames,cluster
having min(logP)>=2;

%OpenSVG_Printer; 
%heatmap4longformatdsd(
dsdin=dsd4heatmap,
xvar=rownames,
yvar=Cluster,
colorvar=logP,
fig_height=500,
fig_width=500,
outline_thickness=2
);
%CloseSVG_Printer;

%let chcker=%FileOrDirExist(/home/cheng.zhong.shan/Macros/mysvgfilename.svg);
%put &chcker;
