%macro OpenSVG_Printer(
filename=mysvgfilename,
svgfileref=out,
other_paras4ods_graphics=%str( ),
outdir=,/*output svg to the dir; if empty, it will save it 
into the dir %sysfunc(pathname(HOME));*/
);

*In Windows, due to sysfunc(pathname(HOME)) only works in Linux;
*the SVG will be failed to be written into the SAS installation dir;
*To address the issue, change the dir into working dir;
%if &sysscp=WIN %then %do;
data _null_;
rx=dlgcdir("%sysfunc(getoption(work))");
run;
%end;
%else %if %length(&outdir)=0 %then %do;
data _null_;
rx=dlgcdir("%sysfunc(pathname(HOME))");
run;
%end;

*Check whether the svg exist;
*add appendix to it to not overwrite previous svg;
%let fi=1;
%let oldname=&filename;
%do %while (%FileOrDirExist(%sysfunc(pathname(HOME))/&filename..svg)=1);
  %put rename your svg output filename as:;
  %let filename=&oldname._&fi;
  %put &filename;
  %let fi=%eval(&fi+1);
%end;

options printerpath=(svg &svgfileref) nobyline;
filename out "&filename..svg";
ods listing close;
ods printer;
ods graphics on/outputfmt=svg
&other_paras4ods_graphics;

%if &sysscp=WIN %then %do;
data _null_;
rx=dlgcdir("%sysfunc(getoption(work))");
run;
%end;
%else %do;
data _null_;
rx=dlgcdir("%sysfunc(pathname(HOME))");
run;
%end;

%mend;

/*Demo:

*Demo1:;
%OpenSVG_Printer(
filename=my_svg,
svgfileref=out,
other_paras4ods_graphics=%str(reset=all height=800 width=400 noborder)
);
*Put your codes here to generate plots;
ods printer close;
*Also need to close the fileref out generated by the macro;
filename out clear;
ods listing;

*Demo2:;
%OpenSVG_Printer;
*Put your codes drawing figures;
ods printer close;
filename out clear;
ods listing;



*/
